name: MacRDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Tailscale
        run: |
          brew install tailscale

      - name: Start Tailscale
        env:
          TS_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscaled &
          sleep 5
          sudo tailscale up --authkey=$TS_AUTHKEY

      - name: Show Tailscale IP
        run: |
          tailscale ip -4
          tailscale status

      - name: Keep machine alive
        uses: mxschmitt/action-tmate@v2
